const categories = [
  {
    eventID: ["Now", "Cuca"],
    name: "Now",
    shortDescription: "Now",
    longDescription: "Now",
    icon: "Now",
    urlImg: "Now",
  },
  {
    eventID: ["Revenge"],
    name: "Revenge",
    shortDescription: "Revenge",
    longDescription: "Revenge",
    icon: "Revenge",
    urlImg: "Revenge",
  },
  {
    eventID: ["ones"],
    name: "ones",
    shortDescription: "ones",
    longDescription: "ones",
    icon: "ones",
    urlImg: "ones",
  },
];
const event = [
  {
    eventCategoryID: ["2132"],
    stageID: ["2222"],
    scheduleID: ["3333"],
    eventName: "Billy Idol",
    artistName: "Billy idol",
    shortDescription: "Music Concert",
    mainDescription: "Round Musical",
    banners: ["4444"],
    videoImg: "billi.png",
    status: null,
    dateEvent: "18:00",
    hourEvent: null,
    urlEvent: null,
    ticketsAvailable: null,
    online: null,
    concertPlacesIMG: null,
    visitorTeam: null,
    homeTeam: null,
    sportType: null,
  },
  {
    eventCategoryID: "3232",
    stageID: "232",
    scheduleID: "ewew",
    eventName: "Billy Idol",
    artistName: "Billy idol",
    shortDescription: "Music Concert",
    mainDescription: "Round Musical",
    banners: "billi.png",
    videoImg: "billi.png",
    dateEvent: "18:00",
  },
  {
    eventCategoryID: "3232",
    stageID: "232",
    scheduleID: "ewew",
    eventName: "Billy Idol",
    artistName: "Billy idol",
    shortDescription: "Music Concert",
    mainDescription: "Round Musical",
    banners: "billi.png",
    videoImg: "billi.png",
    dateEvent: "18:00",
  },
];
export default { event, categories };
