# check the port only for testing

#MUTATION
## partial data (end json) because of the USEREVENTS still not is available only exists user 
@url=http://localhost:4000/
###
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query($offset: Int, $limit: Int, $input: inputOfGetEventByUser) {
  getEventByUser(offset: $offset, limit: $limit, input: $input) {
    user {
      name
      lastName
      firebaseID
      email
      status
      birthday
      role
      telephone
      fullAddress
      country
      city
      gender
      profileImg
    }
    event {
      eventCategoryID {
        categoryType
        name
        shortDescription
        longDescription
        icon
        urlImg
      }
      stageID {
        addressID
        eventCategoryID
        name
        description
        longDescription
        banners
        videoURL
        capacity
        openFrom
        closeTo
        daysOpen
        onlineLink
      }
      scheduleID {
        eventID
        dayNumber
        attendFrom
        attendTo
      }
      eventName
      artistName
      shortDescription
      mainDescription
      banners
      videoImg
      status
      dateEvent
      hourEvent
      urlEvent
      ticketsAvailable
      online
      concertPlacesIMG
      visitorTeam
      homeTeam
      sportType
    }
    eventCost {
      name
      eventID
      description
      section
      cost
      ticketsAvailable
    }
  }
}

{
  "offset": 0,
  "input": {
    "user": {
      "name": "dev",
      "firebaseID": "23948123948123"
    }
  }
}

#QUERY
###
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
