@url=http://localhost:4000/
###
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation CreateTicketToUser($input: inputOfCreateTicket) {
  createTicketToUser(input: $input) {
    userID
    eventID
    ticketTypeID
    buyDate
    type
    ticketCode
    seatName
    status
    isReserved
    
  }
}

{
  "input": {
    "searchUser": {
      "name": "dev",
      "lastName": "dev",
      "firebaseID": "23948123948123",
      "email": "dev@gmail.com"
    },
    "searchEvent": {
      "name": "Concert of Billy Idol",
      "eventID": "6442dfd4e4f3f9c539f6fc62"
    },
    "ticketProps": {
      "buyDate": "03-03-2023",
      "type": "General",
      "ticketCode": "d829dk84fjsh2933",
      "seatName": "23A",
      "status": "current",
      "isReserved": false
    }
  }
}